//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Protell.DAL
{
    public partial class APP_USUARIO
    {
        #region Primitive Properties
    
        public virtual long IdUsuario
        {
            get;
            set;
        }
    
        public virtual string UsuarioCorreo
        {
            get;
            set;
        }
    
        public virtual string UsuarioPwd
        {
            get;
            set;
        }
    
        public virtual string Nombre
        {
            get;
            set;
        }
    
        public virtual string Apellido
        {
            get;
            set;
        }
    
        public virtual string Area
        {
            get;
            set;
        }
    
        public virtual string Puesto
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual bool IsModified
        {
            get;
            set;
        }
    
        public virtual long LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual bool IsNewUser
        {
            get;
            set;
        }
    
        public virtual bool IsVerified
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsMailSent
        {
            get;
            set;
        }
    
        public virtual Nullable<long> ServerLastModifiedDate
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<APP_USUARIO_ROL> APP_USUARIO_ROL
        {
            get
            {
                if (_aPP_USUARIO_ROL == null)
                {
                    var newCollection = new FixupCollection<APP_USUARIO_ROL>();
                    newCollection.CollectionChanged += FixupAPP_USUARIO_ROL;
                    _aPP_USUARIO_ROL = newCollection;
                }
                return _aPP_USUARIO_ROL;
            }
            set
            {
                if (!ReferenceEquals(_aPP_USUARIO_ROL, value))
                {
                    var previousValue = _aPP_USUARIO_ROL as FixupCollection<APP_USUARIO_ROL>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupAPP_USUARIO_ROL;
                    }
                    _aPP_USUARIO_ROL = value;
                    var newValue = value as FixupCollection<APP_USUARIO_ROL>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupAPP_USUARIO_ROL;
                    }
                }
            }
        }
        private ICollection<APP_USUARIO_ROL> _aPP_USUARIO_ROL;
    
        public virtual ICollection<CAT_UPLOAD_LOG> CAT_UPLOAD_LOG
        {
            get
            {
                if (_cAT_UPLOAD_LOG == null)
                {
                    var newCollection = new FixupCollection<CAT_UPLOAD_LOG>();
                    newCollection.CollectionChanged += FixupCAT_UPLOAD_LOG;
                    _cAT_UPLOAD_LOG = newCollection;
                }
                return _cAT_UPLOAD_LOG;
            }
            set
            {
                if (!ReferenceEquals(_cAT_UPLOAD_LOG, value))
                {
                    var previousValue = _cAT_UPLOAD_LOG as FixupCollection<CAT_UPLOAD_LOG>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCAT_UPLOAD_LOG;
                    }
                    _cAT_UPLOAD_LOG = value;
                    var newValue = value as FixupCollection<CAT_UPLOAD_LOG>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCAT_UPLOAD_LOG;
                    }
                }
            }
        }
        private ICollection<CAT_UPLOAD_LOG> _cAT_UPLOAD_LOG;
    
        public virtual ICollection<CAT_SESION> CAT_SESION
        {
            get
            {
                if (_cAT_SESION == null)
                {
                    var newCollection = new FixupCollection<CAT_SESION>();
                    newCollection.CollectionChanged += FixupCAT_SESION;
                    _cAT_SESION = newCollection;
                }
                return _cAT_SESION;
            }
            set
            {
                if (!ReferenceEquals(_cAT_SESION, value))
                {
                    var previousValue = _cAT_SESION as FixupCollection<CAT_SESION>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCAT_SESION;
                    }
                    _cAT_SESION = value;
                    var newValue = value as FixupCollection<CAT_SESION>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCAT_SESION;
                    }
                }
            }
        }
        private ICollection<CAT_SESION> _cAT_SESION;
    
        public virtual ICollection<CI_TRACKING> CI_TRACKING
        {
            get
            {
                if (_cI_TRACKING == null)
                {
                    var newCollection = new FixupCollection<CI_TRACKING>();
                    newCollection.CollectionChanged += FixupCI_TRACKING;
                    _cI_TRACKING = newCollection;
                }
                return _cI_TRACKING;
            }
            set
            {
                if (!ReferenceEquals(_cI_TRACKING, value))
                {
                    var previousValue = _cI_TRACKING as FixupCollection<CI_TRACKING>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCI_TRACKING;
                    }
                    _cI_TRACKING = value;
                    var newValue = value as FixupCollection<CI_TRACKING>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCI_TRACKING;
                    }
                }
            }
        }
        private ICollection<CI_TRACKING> _cI_TRACKING;

        #endregion

        #region Association Fixup
    
        private void FixupAPP_USUARIO_ROL(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (APP_USUARIO_ROL item in e.NewItems)
                {
                    item.APP_USUARIO = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (APP_USUARIO_ROL item in e.OldItems)
                {
                    if (ReferenceEquals(item.APP_USUARIO, this))
                    {
                        item.APP_USUARIO = null;
                    }
                }
            }
        }
    
        private void FixupCAT_UPLOAD_LOG(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CAT_UPLOAD_LOG item in e.NewItems)
                {
                    item.APP_USUARIO = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CAT_UPLOAD_LOG item in e.OldItems)
                {
                    if (ReferenceEquals(item.APP_USUARIO, this))
                    {
                        item.APP_USUARIO = null;
                    }
                }
            }
        }
    
        private void FixupCAT_SESION(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CAT_SESION item in e.NewItems)
                {
                    item.APP_USUARIO = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CAT_SESION item in e.OldItems)
                {
                    if (ReferenceEquals(item.APP_USUARIO, this))
                    {
                        item.APP_USUARIO = null;
                    }
                }
            }
        }
    
        private void FixupCI_TRACKING(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CI_TRACKING item in e.NewItems)
                {
                    item.APP_USUARIO = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CI_TRACKING item in e.OldItems)
                {
                    if (ReferenceEquals(item.APP_USUARIO, this))
                    {
                        item.APP_USUARIO = null;
                    }
                }
            }
        }

        #endregion

    }
}
