//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Protell.DAL
{
    public partial class APP_BITACORA
    {
        #region Primitive Properties
    
        public virtual long IdBitacora
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Fecha
        {
            get;
            set;
        }
    
        public virtual string Metodo
        {
            get;
            set;
        }
    
        public virtual string Mensaje
        {
            get;
            set;
        }

        #endregion

    }
}
