//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Protell.DAL
{
    public partial class APP_USUARIO_ROL
    {
        #region Primitive Properties
    
        public virtual long IdUsuario
        {
            get { return _idUsuario; }
            set
            {
                if (_idUsuario != value)
                {
                    if (APP_USUARIO != null && APP_USUARIO.IdUsuario != value)
                    {
                        APP_USUARIO = null;
                    }
                    _idUsuario = value;
                }
            }
        }
        private long _idUsuario;
    
        public virtual long IdRol
        {
            get { return _idRol; }
            set
            {
                if (_idRol != value)
                {
                    if (APP_ROL != null && APP_ROL.IdRol != value)
                    {
                        APP_ROL = null;
                    }
                    _idRol = value;
                }
            }
        }
        private long _idRol;
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual long LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual bool IsModified
        {
            get;
            set;
        }
    
        public virtual Nullable<long> ServerLastModifiedDate
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual APP_ROL APP_ROL
        {
            get { return _aPP_ROL; }
            set
            {
                if (!ReferenceEquals(_aPP_ROL, value))
                {
                    var previousValue = _aPP_ROL;
                    _aPP_ROL = value;
                    FixupAPP_ROL(previousValue);
                }
            }
        }
        private APP_ROL _aPP_ROL;
    
        public virtual APP_USUARIO APP_USUARIO
        {
            get { return _aPP_USUARIO; }
            set
            {
                if (!ReferenceEquals(_aPP_USUARIO, value))
                {
                    var previousValue = _aPP_USUARIO;
                    _aPP_USUARIO = value;
                    FixupAPP_USUARIO(previousValue);
                }
            }
        }
        private APP_USUARIO _aPP_USUARIO;

        #endregion

        #region Association Fixup
    
        private void FixupAPP_ROL(APP_ROL previousValue)
        {
            if (previousValue != null && previousValue.APP_USUARIO_ROL.Contains(this))
            {
                previousValue.APP_USUARIO_ROL.Remove(this);
            }
    
            if (APP_ROL != null)
            {
                if (!APP_ROL.APP_USUARIO_ROL.Contains(this))
                {
                    APP_ROL.APP_USUARIO_ROL.Add(this);
                }
                if (IdRol != APP_ROL.IdRol)
                {
                    IdRol = APP_ROL.IdRol;
                }
            }
        }
    
        private void FixupAPP_USUARIO(APP_USUARIO previousValue)
        {
            if (previousValue != null && previousValue.APP_USUARIO_ROL.Contains(this))
            {
                previousValue.APP_USUARIO_ROL.Remove(this);
            }
    
            if (APP_USUARIO != null)
            {
                if (!APP_USUARIO.APP_USUARIO_ROL.Contains(this))
                {
                    APP_USUARIO.APP_USUARIO_ROL.Add(this);
                }
                if (IdUsuario != APP_USUARIO.IdUsuario)
                {
                    IdUsuario = APP_USUARIO.IdUsuario;
                }
            }
        }

        #endregion

    }
}
