//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Protell.DAL
{
    public partial class CAT_SYNC_LOG
    {
        #region Primitive Properties
    
        public virtual long IdSyncLog
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> FechaSinc
        {
            get;
            set;
        }
    
        public virtual string Hora
        {
            get;
            set;
        }
    
        public virtual string Menssage
        {
            get;
            set;
        }
    
        public virtual string Exception
        {
            get;
            set;
        }

        #endregion

    }
}
