//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Protell.DAL
{
    public partial class CAT_CONDPRO
    {
        #region Primitive Properties
    
        public virtual long IdCondicion
        {
            get;
            set;
        }
    
        public virtual string CondicionName
        {
            get;
            set;
        }
    
        public virtual string PathCodicion
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual bool IsModified
        {
            get;
            set;
        }
    
        public virtual long LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<long> ServerLastModifiedDate
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<CI_REGISTRO> CI_REGISTRO
        {
            get
            {
                if (_cI_REGISTRO == null)
                {
                    var newCollection = new FixupCollection<CI_REGISTRO>();
                    newCollection.CollectionChanged += FixupCI_REGISTRO;
                    _cI_REGISTRO = newCollection;
                }
                return _cI_REGISTRO;
            }
            set
            {
                if (!ReferenceEquals(_cI_REGISTRO, value))
                {
                    var previousValue = _cI_REGISTRO as FixupCollection<CI_REGISTRO>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCI_REGISTRO;
                    }
                    _cI_REGISTRO = value;
                    var newValue = value as FixupCollection<CI_REGISTRO>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCI_REGISTRO;
                    }
                }
            }
        }
        private ICollection<CI_REGISTRO> _cI_REGISTRO;
    
        public virtual ICollection<CAT_OPERACION_ESTRUCTURA> CAT_OPERACION_ESTRUCTURA
        {
            get
            {
                if (_cAT_OPERACION_ESTRUCTURA == null)
                {
                    var newCollection = new FixupCollection<CAT_OPERACION_ESTRUCTURA>();
                    newCollection.CollectionChanged += FixupCAT_OPERACION_ESTRUCTURA;
                    _cAT_OPERACION_ESTRUCTURA = newCollection;
                }
                return _cAT_OPERACION_ESTRUCTURA;
            }
            set
            {
                if (!ReferenceEquals(_cAT_OPERACION_ESTRUCTURA, value))
                {
                    var previousValue = _cAT_OPERACION_ESTRUCTURA as FixupCollection<CAT_OPERACION_ESTRUCTURA>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCAT_OPERACION_ESTRUCTURA;
                    }
                    _cAT_OPERACION_ESTRUCTURA = value;
                    var newValue = value as FixupCollection<CAT_OPERACION_ESTRUCTURA>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCAT_OPERACION_ESTRUCTURA;
                    }
                }
            }
        }
        private ICollection<CAT_OPERACION_ESTRUCTURA> _cAT_OPERACION_ESTRUCTURA;

        #endregion

        #region Association Fixup
    
        private void FixupCI_REGISTRO(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CI_REGISTRO item in e.NewItems)
                {
                    item.CAT_CONDPRO = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CI_REGISTRO item in e.OldItems)
                {
                    if (ReferenceEquals(item.CAT_CONDPRO, this))
                    {
                        item.CAT_CONDPRO = null;
                    }
                }
            }
        }
    
        private void FixupCAT_OPERACION_ESTRUCTURA(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CAT_OPERACION_ESTRUCTURA item in e.NewItems)
                {
                    item.CAT_CONDPRO = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CAT_OPERACION_ESTRUCTURA item in e.OldItems)
                {
                    if (ReferenceEquals(item.CAT_CONDPRO, this))
                    {
                        item.CAT_CONDPRO = null;
                    }
                }
            }
        }

        #endregion

    }
}
