//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Protell.DAL
{
    public partial class CAT_SESION
    {
        #region Primitive Properties
    
        public virtual long IdSesion
        {
            get;
            set;
        }
    
        public virtual Nullable<long> IdUsuario
        {
            get { return _idUsuario; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_idUsuario != value)
                    {
                        if (APP_USUARIO != null && APP_USUARIO.IdUsuario != value)
                        {
                            APP_USUARIO = null;
                        }
                        _idUsuario = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<long> _idUsuario;
    
        public virtual Nullable<bool> IsSaveSesion
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual APP_USUARIO APP_USUARIO
        {
            get { return _aPP_USUARIO; }
            set
            {
                if (!ReferenceEquals(_aPP_USUARIO, value))
                {
                    var previousValue = _aPP_USUARIO;
                    _aPP_USUARIO = value;
                    FixupAPP_USUARIO(previousValue);
                }
            }
        }
        private APP_USUARIO _aPP_USUARIO;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupAPP_USUARIO(APP_USUARIO previousValue)
        {
            if (previousValue != null && previousValue.CAT_SESION.Contains(this))
            {
                previousValue.CAT_SESION.Remove(this);
            }
    
            if (APP_USUARIO != null)
            {
                if (!APP_USUARIO.CAT_SESION.Contains(this))
                {
                    APP_USUARIO.CAT_SESION.Add(this);
                }
                if (IdUsuario != APP_USUARIO.IdUsuario)
                {
                    IdUsuario = APP_USUARIO.IdUsuario;
                }
            }
            else if (!_settingFK)
            {
                IdUsuario = null;
            }
        }

        #endregion

    }
}
