//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Protell.DAL
{
    public partial class TMP_CI_REGISTRO_CONFIRMATION
    {
        #region Primitive Properties
    
        public virtual long IdRegistro
        {
            get;
            set;
        }
    
        public virtual long IdPuntoMedicion
        {
            get;
            set;
        }
    
        public virtual long FechaNumerica
        {
            get;
            set;
        }
    
        public virtual Nullable<long> LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<long> ServerLastModifiedDate
        {
            get;
            set;
        }

        #endregion

    }
}
