//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
namespace Protell.Server.DAL.POCOS
{
    public partial class CAT_OPERACION_ESTRUCTURA_V2
    {
        #region Primitive Properties

        public virtual long IdOperacionEstructura
        {
            get;
            set;
        }

        public virtual long IdCondicion
        {
            get;
            set;
        }

        public virtual long IdEstructura
        {
            get;
            set;
        }

        public virtual string OperacionEstrucuturaName
        {
            get;
            set;
        }

        public virtual bool IsActive
        {
            get;
            set;
        }

        public virtual bool IsModified
        {
            get;
            set;
        }

        public virtual long LastModifiedDate
        {
            get;
            set;
        }

        public virtual long ServerLastModifiedDate
        {
            get;
            set;
        }

        #endregion
    }
}
