//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Protell.Server.DAL.POCOS
{
    public partial class CAT_SISTEMA
    {
        #region Primitive Properties
    
        public virtual long IdSistema
        {
            get;
            set;
        }
    
        public virtual string SistemaName
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual bool IsModified
        {
            get;
            set;
        }
    
        public virtual long LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<long> ServerLastModifiedDate
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<CAT_ESTRUCTURA> CAT_ESTRUCTURA
        {
            get
            {
                if (_cAT_ESTRUCTURA == null)
                {
                    var newCollection = new FixupCollection<CAT_ESTRUCTURA>();
                    newCollection.CollectionChanged += FixupCAT_ESTRUCTURA;
                    _cAT_ESTRUCTURA = newCollection;
                }
                return _cAT_ESTRUCTURA;
            }
            set
            {
                if (!ReferenceEquals(_cAT_ESTRUCTURA, value))
                {
                    var previousValue = _cAT_ESTRUCTURA as FixupCollection<CAT_ESTRUCTURA>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCAT_ESTRUCTURA;
                    }
                    _cAT_ESTRUCTURA = value;
                    var newValue = value as FixupCollection<CAT_ESTRUCTURA>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCAT_ESTRUCTURA;
                    }
                }
            }
        }
        private ICollection<CAT_ESTRUCTURA> _cAT_ESTRUCTURA;

        #endregion

        #region Association Fixup
    
        private void FixupCAT_ESTRUCTURA(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CAT_ESTRUCTURA item in e.NewItems)
                {
                    item.CAT_SISTEMA = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CAT_ESTRUCTURA item in e.OldItems)
                {
                    if (ReferenceEquals(item.CAT_SISTEMA, this))
                    {
                        item.CAT_SISTEMA = null;
                    }
                }
            }
        }

        #endregion

    }
}
