//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Protell.Server.DAL.POCOS
{
    public partial class CAT_DEPENDENCIA
    {
        #region Primitive Properties
    
        public virtual long IdDependencia
        {
            get;
            set;
        }
    
        public virtual string DependenciaName
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual bool IsModified
        {
            get;
            set;
        }
    
        public virtual long LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<long> ServerLastModifiedDate
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<REL_ESTRUCTURA_DEPENDENCIA> REL_ESTRUCTURA_DEPENDENCIA
        {
            get
            {
                if (_rEL_ESTRUCTURA_DEPENDENCIA == null)
                {
                    var newCollection = new FixupCollection<REL_ESTRUCTURA_DEPENDENCIA>();
                    newCollection.CollectionChanged += FixupREL_ESTRUCTURA_DEPENDENCIA;
                    _rEL_ESTRUCTURA_DEPENDENCIA = newCollection;
                }
                return _rEL_ESTRUCTURA_DEPENDENCIA;
            }
            set
            {
                if (!ReferenceEquals(_rEL_ESTRUCTURA_DEPENDENCIA, value))
                {
                    var previousValue = _rEL_ESTRUCTURA_DEPENDENCIA as FixupCollection<REL_ESTRUCTURA_DEPENDENCIA>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupREL_ESTRUCTURA_DEPENDENCIA;
                    }
                    _rEL_ESTRUCTURA_DEPENDENCIA = value;
                    var newValue = value as FixupCollection<REL_ESTRUCTURA_DEPENDENCIA>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupREL_ESTRUCTURA_DEPENDENCIA;
                    }
                }
            }
        }
        private ICollection<REL_ESTRUCTURA_DEPENDENCIA> _rEL_ESTRUCTURA_DEPENDENCIA;

        #endregion

        #region Association Fixup
    
        private void FixupREL_ESTRUCTURA_DEPENDENCIA(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (REL_ESTRUCTURA_DEPENDENCIA item in e.NewItems)
                {
                    item.CAT_DEPENDENCIA = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (REL_ESTRUCTURA_DEPENDENCIA item in e.OldItems)
                {
                    if (ReferenceEquals(item.CAT_DEPENDENCIA, this))
                    {
                        item.CAT_DEPENDENCIA = null;
                    }
                }
            }
        }

        #endregion

    }
}
