//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Protell.Server.DAL.POCOS
{
    public partial class CAT_UPLOAD_LOG
    {
        #region Primitive Properties
    
        public virtual long IdUploadLog
        {
            get;
            set;
        }
    
        public virtual string Msg
        {
            get;
            set;
        }
    
        public virtual string IpDir
        {
            get;
            set;
        }
    
        public virtual string PcName
        {
            get;
            set;
        }
    
        public virtual long IdUsuario
        {
            get { return _idUsuario; }
            set
            {
                if (_idUsuario != value)
                {
                    if (APP_USUARIO != null && APP_USUARIO.IdUsuario != value)
                    {
                        APP_USUARIO = null;
                    }
                    _idUsuario = value;
                }
            }
        }
        private long _idUsuario;

        #endregion

        #region Navigation Properties
    
        public virtual APP_USUARIO APP_USUARIO
        {
            get { return _aPP_USUARIO; }
            set
            {
                if (!ReferenceEquals(_aPP_USUARIO, value))
                {
                    var previousValue = _aPP_USUARIO;
                    _aPP_USUARIO = value;
                    FixupAPP_USUARIO(previousValue);
                }
            }
        }
        private APP_USUARIO _aPP_USUARIO;

        #endregion

        #region Association Fixup
    
        private void FixupAPP_USUARIO(APP_USUARIO previousValue)
        {
            if (previousValue != null && previousValue.CAT_UPLOAD_LOG.Contains(this))
            {
                previousValue.CAT_UPLOAD_LOG.Remove(this);
            }
    
            if (APP_USUARIO != null)
            {
                if (!APP_USUARIO.CAT_UPLOAD_LOG.Contains(this))
                {
                    APP_USUARIO.CAT_UPLOAD_LOG.Add(this);
                }
                if (IdUsuario != APP_USUARIO.IdUsuario)
                {
                    IdUsuario = APP_USUARIO.IdUsuario;
                }
            }
        }

        #endregion

    }
}
