//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Protell.Server.DAL.POCOS
{
    public partial class EXT_PUNTO_MEDICION_PARAMETRO_MEDICION
    {
        #region Primitive Properties
    
        public virtual long IdPuntoMedicion
        {
            get;
            set;
        }
    
        public virtual string ParametroMedicion
        {
            get;
            set;
        }

        #endregion

    }
}
