//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Protell.Server.DAL.POCOS
{
    public partial class SP_CatPuntoMedicionSelect_Result5
    {
        #region Primitive Properties
    
        public long IdPuntoMedicion
        {
            get;
            set;
        }
    
        public string PuntoMedicionName
        {
            get;
            set;
        }
    
        public Nullable<long> IdUnidadMedida
        {
            get;
            set;
        }
    
        public string UnidadMedidaName
        {
            get;
            set;
        }
    
        public long IdTipoPuntoMedicion
        {
            get;
            set;
        }
    
        public string TipoPuntoMedicionName
        {
            get;
            set;
        }
    
        public Nullable<double> ValorReferencia
        {
            get;
            set;
        }
    
        public Nullable<int> ParametroReferencia
        {
            get;
            set;
        }
    
        public Nullable<double> latiitud
        {
            get;
            set;
        }
    
        public Nullable<double> longitud
        {
            get;
            set;
        }
    
        public Nullable<long> IdDependencia
        {
            get;
            set;
        }
    
        public string DependenciaName
        {
            get;
            set;
        }
    
        public string Zona
        {
            get;
            set;
        }
    
        public Nullable<double> ValorFactor
        {
            get;
            set;
        }
    
        public Nullable<long> IdAccionActual
        {
            get;
            set;
        }
    
        public string AccionAcualName
        {
            get;
            set;
        }
    
        public Nullable<double> Max
        {
            get;
            set;
        }
    
        public Nullable<double> Min
        {
            get;
            set;
        }
    
        public Nullable<long> IdRol
        {
            get;
            set;
        }
    
        public string RolName
        {
            get;
            set;
        }
    
        public string SistemaName
        {
            get;
            set;
        }

        #endregion

    }
}
