//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Protell.Server.DAL.POCOS
{
    public partial class wappSpValidateMail_Result1
    {
        #region Primitive Properties
    
        public Nullable<long> IdUsuario
        {
            get;
            set;
        }
    
        public string IdSesion
        {
            get;
            set;
        }

        #endregion

    }
}
