//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Protell.DAL
{
    public partial class APP_ROL_MENU
    {
        #region Primitive Properties
    
        public virtual long IdRol
        {
            get { return _idRol; }
            set
            {
                if (_idRol != value)
                {
                    if (APP_ROL != null && APP_ROL.IdRol != value)
                    {
                        APP_ROL = null;
                    }
                    _idRol = value;
                }
            }
        }
        private long _idRol;
    
        public virtual long IdMenu
        {
            get { return _idMenu; }
            set
            {
                if (_idMenu != value)
                {
                    if (APP_MENU != null && APP_MENU.IdMenu != value)
                    {
                        APP_MENU = null;
                    }
                    _idMenu = value;
                }
            }
        }
        private long _idMenu;
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual bool IsModified
        {
            get;
            set;
        }
    
        public virtual long LastModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual APP_MENU APP_MENU
        {
            get { return _aPP_MENU; }
            set
            {
                if (!ReferenceEquals(_aPP_MENU, value))
                {
                    var previousValue = _aPP_MENU;
                    _aPP_MENU = value;
                    FixupAPP_MENU(previousValue);
                }
            }
        }
        private APP_MENU _aPP_MENU;
    
        public virtual APP_ROL APP_ROL
        {
            get { return _aPP_ROL; }
            set
            {
                if (!ReferenceEquals(_aPP_ROL, value))
                {
                    var previousValue = _aPP_ROL;
                    _aPP_ROL = value;
                    FixupAPP_ROL(previousValue);
                }
            }
        }
        private APP_ROL _aPP_ROL;

        #endregion
        #region Association Fixup
    
        private void FixupAPP_MENU(APP_MENU previousValue)
        {
            if (previousValue != null && previousValue.APP_ROL_MENU.Contains(this))
            {
                previousValue.APP_ROL_MENU.Remove(this);
            }
    
            if (APP_MENU != null)
            {
                if (!APP_MENU.APP_ROL_MENU.Contains(this))
                {
                    APP_MENU.APP_ROL_MENU.Add(this);
                }
                if (IdMenu != APP_MENU.IdMenu)
                {
                    IdMenu = APP_MENU.IdMenu;
                }
            }
        }
    
        private void FixupAPP_ROL(APP_ROL previousValue)
        {
            if (previousValue != null && previousValue.APP_ROL_MENU.Contains(this))
            {
                previousValue.APP_ROL_MENU.Remove(this);
            }
    
            if (APP_ROL != null)
            {
                if (!APP_ROL.APP_ROL_MENU.Contains(this))
                {
                    APP_ROL.APP_ROL_MENU.Add(this);
                }
                if (IdRol != APP_ROL.IdRol)
                {
                    IdRol = APP_ROL.IdRol;
                }
            }
        }

        #endregion
    }
}
