//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Protell.DAL
{
    public partial class CAT_CONSIDERACION
    {
        #region Primitive Properties
    
        public virtual long IdConsideracion
        {
            get;
            set;
        }
    
        public virtual string ConsideracionName
        {
            get;
            set;
        }
    
        public virtual string ConsideracionDesc
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual bool IsModified
        {
            get;
            set;
        }
    
        public virtual long LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual long IdCondicion
        {
            get { return _idCondicion; }
            set
            {
                if (_idCondicion != value)
                {
                    if (CAT_CONDPRO != null && CAT_CONDPRO.IdCondicion != value)
                    {
                        CAT_CONDPRO = null;
                    }
                    _idCondicion = value;
                }
            }
        }
        private long _idCondicion;

        #endregion
        #region Navigation Properties
    
        public virtual CAT_CONDPRO CAT_CONDPRO
        {
            get { return _cAT_CONDPRO; }
            set
            {
                if (!ReferenceEquals(_cAT_CONDPRO, value))
                {
                    var previousValue = _cAT_CONDPRO;
                    _cAT_CONDPRO = value;
                    FixupCAT_CONDPRO(previousValue);
                }
            }
        }
        private CAT_CONDPRO _cAT_CONDPRO;

        #endregion
        #region Association Fixup
    
        private void FixupCAT_CONDPRO(CAT_CONDPRO previousValue)
        {
            if (previousValue != null && previousValue.CAT_CONSIDERACION.Contains(this))
            {
                previousValue.CAT_CONSIDERACION.Remove(this);
            }
    
            if (CAT_CONDPRO != null)
            {
                if (!CAT_CONDPRO.CAT_CONSIDERACION.Contains(this))
                {
                    CAT_CONDPRO.CAT_CONSIDERACION.Add(this);
                }
                if (IdCondicion != CAT_CONDPRO.IdCondicion)
                {
                    IdCondicion = CAT_CONDPRO.IdCondicion;
                }
            }
        }

        #endregion
    }
}
