//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Protell.DAL
{
    public partial class INF_INFODOC
    {
        #region Primitive Properties
    
        public virtual long IdInfoDoc
        {
            get;
            set;
        }
    
        public virtual long IdRol
        {
            get { return _idRol; }
            set
            {
                if (_idRol != value)
                {
                    if (APP_ROL != null && APP_ROL.IdRol != value)
                    {
                        APP_ROL = null;
                    }
                    _idRol = value;
                }
            }
        }
        private long _idRol;
    
        public virtual long IdUsuario
        {
            get { return _idUsuario; }
            set
            {
                if (_idUsuario != value)
                {
                    if (APP_USUARIO != null && APP_USUARIO.IdUsuario != value)
                    {
                        APP_USUARIO = null;
                    }
                    _idUsuario = value;
                }
            }
        }
        private long _idUsuario;
    
        public virtual long IdForm
        {
            get { return _idForm; }
            set
            {
                if (_idForm != value)
                {
                    if (INF_FORM != null && INF_FORM.IdForm != value)
                    {
                        INF_FORM = null;
                    }
                    _idForm = value;
                }
            }
        }
        private long _idForm;
    
        public virtual long IdAccion
        {
            get { return _idAccion; }
            set
            {
                if (_idAccion != value)
                {
                    if (INF_ACCION != null && INF_ACCION.IdAccion != value)
                    {
                        INF_ACCION = null;
                    }
                    _idAccion = value;
                }
            }
        }
        private long _idAccion;
    
        public virtual long Fecha
        {
            get;
            set;
        }
    
        public virtual long IdRef
        {
            get;
            set;
        }
    
        public virtual string IpAddress
        {
            get;
            set;
        }
    
        public virtual string MacAdress
        {
            get;
            set;
        }
    
        public virtual string PcName
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual bool IsModified
        {
            get;
            set;
        }
    
        public virtual long LastModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual APP_ROL APP_ROL
        {
            get { return _aPP_ROL; }
            set
            {
                if (!ReferenceEquals(_aPP_ROL, value))
                {
                    var previousValue = _aPP_ROL;
                    _aPP_ROL = value;
                    FixupAPP_ROL(previousValue);
                }
            }
        }
        private APP_ROL _aPP_ROL;
    
        public virtual APP_USUARIO APP_USUARIO
        {
            get { return _aPP_USUARIO; }
            set
            {
                if (!ReferenceEquals(_aPP_USUARIO, value))
                {
                    var previousValue = _aPP_USUARIO;
                    _aPP_USUARIO = value;
                    FixupAPP_USUARIO(previousValue);
                }
            }
        }
        private APP_USUARIO _aPP_USUARIO;
    
        public virtual INF_ACCION INF_ACCION
        {
            get { return _iNF_ACCION; }
            set
            {
                if (!ReferenceEquals(_iNF_ACCION, value))
                {
                    var previousValue = _iNF_ACCION;
                    _iNF_ACCION = value;
                    FixupINF_ACCION(previousValue);
                }
            }
        }
        private INF_ACCION _iNF_ACCION;
    
        public virtual INF_FORM INF_FORM
        {
            get { return _iNF_FORM; }
            set
            {
                if (!ReferenceEquals(_iNF_FORM, value))
                {
                    var previousValue = _iNF_FORM;
                    _iNF_FORM = value;
                    FixupINF_FORM(previousValue);
                }
            }
        }
        private INF_FORM _iNF_FORM;

        #endregion
        #region Association Fixup
    
        private void FixupAPP_ROL(APP_ROL previousValue)
        {
            if (previousValue != null && previousValue.INF_INFODOC.Contains(this))
            {
                previousValue.INF_INFODOC.Remove(this);
            }
    
            if (APP_ROL != null)
            {
                if (!APP_ROL.INF_INFODOC.Contains(this))
                {
                    APP_ROL.INF_INFODOC.Add(this);
                }
                if (IdRol != APP_ROL.IdRol)
                {
                    IdRol = APP_ROL.IdRol;
                }
            }
        }
    
        private void FixupAPP_USUARIO(APP_USUARIO previousValue)
        {
            if (previousValue != null && previousValue.INF_INFODOC.Contains(this))
            {
                previousValue.INF_INFODOC.Remove(this);
            }
    
            if (APP_USUARIO != null)
            {
                if (!APP_USUARIO.INF_INFODOC.Contains(this))
                {
                    APP_USUARIO.INF_INFODOC.Add(this);
                }
                if (IdUsuario != APP_USUARIO.IdUsuario)
                {
                    IdUsuario = APP_USUARIO.IdUsuario;
                }
            }
        }
    
        private void FixupINF_ACCION(INF_ACCION previousValue)
        {
            if (previousValue != null && previousValue.INF_INFODOC.Contains(this))
            {
                previousValue.INF_INFODOC.Remove(this);
            }
    
            if (INF_ACCION != null)
            {
                if (!INF_ACCION.INF_INFODOC.Contains(this))
                {
                    INF_ACCION.INF_INFODOC.Add(this);
                }
                if (IdAccion != INF_ACCION.IdAccion)
                {
                    IdAccion = INF_ACCION.IdAccion;
                }
            }
        }
    
        private void FixupINF_FORM(INF_FORM previousValue)
        {
            if (previousValue != null && previousValue.INF_INFODOC.Contains(this))
            {
                previousValue.INF_INFODOC.Remove(this);
            }
    
            if (INF_FORM != null)
            {
                if (!INF_FORM.INF_INFODOC.Contains(this))
                {
                    INF_FORM.INF_INFODOC.Add(this);
                }
                if (IdForm != INF_FORM.IdForm)
                {
                    IdForm = INF_FORM.IdForm;
                }
            }
        }

        #endregion
    }
}
