//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Protell.DAL
{
    public partial class REL_ESTRUCTURA_DEPENDENCIA
    {
        #region Primitive Properties
    
        public virtual long IdEstructuraDependencia
        {
            get;
            set;
        }
    
        public virtual long IdDependencia
        {
            get { return _idDependencia; }
            set
            {
                if (_idDependencia != value)
                {
                    if (CAT_DEPENDENCIA != null && CAT_DEPENDENCIA.IdDependencia != value)
                    {
                        CAT_DEPENDENCIA = null;
                    }
                    _idDependencia = value;
                }
            }
        }
        private long _idDependencia;
    
        public virtual long IdEstructura
        {
            get { return _idEstructura; }
            set
            {
                if (_idEstructura != value)
                {
                    if (CAT_ESTRUCTURA != null && CAT_ESTRUCTURA.IdEstructura != value)
                    {
                        CAT_ESTRUCTURA = null;
                    }
                    _idEstructura = value;
                }
            }
        }
        private long _idEstructura;
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual bool IsModified
        {
            get;
            set;
        }
    
        public virtual long LastModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual CAT_DEPENDENCIA CAT_DEPENDENCIA
        {
            get { return _cAT_DEPENDENCIA; }
            set
            {
                if (!ReferenceEquals(_cAT_DEPENDENCIA, value))
                {
                    var previousValue = _cAT_DEPENDENCIA;
                    _cAT_DEPENDENCIA = value;
                    FixupCAT_DEPENDENCIA(previousValue);
                }
            }
        }
        private CAT_DEPENDENCIA _cAT_DEPENDENCIA;
    
        public virtual CAT_ESTRUCTURA CAT_ESTRUCTURA
        {
            get { return _cAT_ESTRUCTURA; }
            set
            {
                if (!ReferenceEquals(_cAT_ESTRUCTURA, value))
                {
                    var previousValue = _cAT_ESTRUCTURA;
                    _cAT_ESTRUCTURA = value;
                    FixupCAT_ESTRUCTURA(previousValue);
                }
            }
        }
        private CAT_ESTRUCTURA _cAT_ESTRUCTURA;

        #endregion
        #region Association Fixup
    
        private void FixupCAT_DEPENDENCIA(CAT_DEPENDENCIA previousValue)
        {
            if (previousValue != null && previousValue.REL_ESTRUCTURA_DEPENDENCIA.Contains(this))
            {
                previousValue.REL_ESTRUCTURA_DEPENDENCIA.Remove(this);
            }
    
            if (CAT_DEPENDENCIA != null)
            {
                if (!CAT_DEPENDENCIA.REL_ESTRUCTURA_DEPENDENCIA.Contains(this))
                {
                    CAT_DEPENDENCIA.REL_ESTRUCTURA_DEPENDENCIA.Add(this);
                }
                if (IdDependencia != CAT_DEPENDENCIA.IdDependencia)
                {
                    IdDependencia = CAT_DEPENDENCIA.IdDependencia;
                }
            }
        }
    
        private void FixupCAT_ESTRUCTURA(CAT_ESTRUCTURA previousValue)
        {
            if (previousValue != null && previousValue.REL_ESTRUCTURA_DEPENDENCIA.Contains(this))
            {
                previousValue.REL_ESTRUCTURA_DEPENDENCIA.Remove(this);
            }
    
            if (CAT_ESTRUCTURA != null)
            {
                if (!CAT_ESTRUCTURA.REL_ESTRUCTURA_DEPENDENCIA.Contains(this))
                {
                    CAT_ESTRUCTURA.REL_ESTRUCTURA_DEPENDENCIA.Add(this);
                }
                if (IdEstructura != CAT_ESTRUCTURA.IdEstructura)
                {
                    IdEstructura = CAT_ESTRUCTURA.IdEstructura;
                }
            }
        }

        #endregion
    }
}
