//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Protell.DAL
{
    public partial class REL_ACCION_PROTOCOLO
    {
        #region Primitive Properties
    
        public virtual long IdAccionProtocolo
        {
            get;
            set;
        }
    
        public virtual long IdCondicion
        {
            get { return _idCondicion; }
            set
            {
                if (_idCondicion != value)
                {
                    if (CAT_CONDPRO != null && CAT_CONDPRO.IdCondicion != value)
                    {
                        CAT_CONDPRO = null;
                    }
                    _idCondicion = value;
                }
            }
        }
        private long _idCondicion;
    
        public virtual long IdEstructura
        {
            get { return _idEstructura; }
            set
            {
                if (_idEstructura != value)
                {
                    if (CAT_ESTRUCTURA != null && CAT_ESTRUCTURA.IdEstructura != value)
                    {
                        CAT_ESTRUCTURA = null;
                    }
                    _idEstructura = value;
                }
            }
        }
        private long _idEstructura;
    
        public virtual string AccionProtocoloDesc
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual bool IsModified
        {
            get;
            set;
        }
    
        public virtual long LastModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual CAT_CONDPRO CAT_CONDPRO
        {
            get { return _cAT_CONDPRO; }
            set
            {
                if (!ReferenceEquals(_cAT_CONDPRO, value))
                {
                    var previousValue = _cAT_CONDPRO;
                    _cAT_CONDPRO = value;
                    FixupCAT_CONDPRO(previousValue);
                }
            }
        }
        private CAT_CONDPRO _cAT_CONDPRO;
    
        public virtual CAT_ESTRUCTURA CAT_ESTRUCTURA
        {
            get { return _cAT_ESTRUCTURA; }
            set
            {
                if (!ReferenceEquals(_cAT_ESTRUCTURA, value))
                {
                    var previousValue = _cAT_ESTRUCTURA;
                    _cAT_ESTRUCTURA = value;
                    FixupCAT_ESTRUCTURA(previousValue);
                }
            }
        }
        private CAT_ESTRUCTURA _cAT_ESTRUCTURA;

        #endregion
        #region Association Fixup
    
        private void FixupCAT_CONDPRO(CAT_CONDPRO previousValue)
        {
            if (previousValue != null && previousValue.REL_ACCION_PROTOCOLO.Contains(this))
            {
                previousValue.REL_ACCION_PROTOCOLO.Remove(this);
            }
    
            if (CAT_CONDPRO != null)
            {
                if (!CAT_CONDPRO.REL_ACCION_PROTOCOLO.Contains(this))
                {
                    CAT_CONDPRO.REL_ACCION_PROTOCOLO.Add(this);
                }
                if (IdCondicion != CAT_CONDPRO.IdCondicion)
                {
                    IdCondicion = CAT_CONDPRO.IdCondicion;
                }
            }
        }
    
        private void FixupCAT_ESTRUCTURA(CAT_ESTRUCTURA previousValue)
        {
            if (previousValue != null && previousValue.REL_ACCION_PROTOCOLO.Contains(this))
            {
                previousValue.REL_ACCION_PROTOCOLO.Remove(this);
            }
    
            if (CAT_ESTRUCTURA != null)
            {
                if (!CAT_ESTRUCTURA.REL_ACCION_PROTOCOLO.Contains(this))
                {
                    CAT_ESTRUCTURA.REL_ACCION_PROTOCOLO.Add(this);
                }
                if (IdEstructura != CAT_ESTRUCTURA.IdEstructura)
                {
                    IdEstructura = CAT_ESTRUCTURA.IdEstructura;
                }
            }
        }

        #endregion
    }
}
