//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Protell.DAL
{
    public partial class REL_EST_PUNTOMED
    {
        #region Primitive Properties
    
        public virtual long IdEstPuntoMed
        {
            get;
            set;
        }
    
        public virtual long IdEstructura
        {
            get { return _idEstructura; }
            set
            {
                if (_idEstructura != value)
                {
                    if (CAT_ESTRUCTURA != null && CAT_ESTRUCTURA.IdEstructura != value)
                    {
                        CAT_ESTRUCTURA = null;
                    }
                    _idEstructura = value;
                }
            }
        }
        private long _idEstructura;
    
        public virtual long IdPuntoMedicion
        {
            get { return _idPuntoMedicion; }
            set
            {
                if (_idPuntoMedicion != value)
                {
                    if (CAT_PUNTO_MEDICION != null && CAT_PUNTO_MEDICION.IdPuntoMedicion != value)
                    {
                        CAT_PUNTO_MEDICION = null;
                    }
                    _idPuntoMedicion = value;
                }
            }
        }
        private long _idPuntoMedicion;
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual bool IsModified
        {
            get;
            set;
        }
    
        public virtual long LastModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual CAT_ESTRUCTURA CAT_ESTRUCTURA
        {
            get { return _cAT_ESTRUCTURA; }
            set
            {
                if (!ReferenceEquals(_cAT_ESTRUCTURA, value))
                {
                    var previousValue = _cAT_ESTRUCTURA;
                    _cAT_ESTRUCTURA = value;
                    FixupCAT_ESTRUCTURA(previousValue);
                }
            }
        }
        private CAT_ESTRUCTURA _cAT_ESTRUCTURA;
    
        public virtual CAT_PUNTO_MEDICION CAT_PUNTO_MEDICION
        {
            get { return _cAT_PUNTO_MEDICION; }
            set
            {
                if (!ReferenceEquals(_cAT_PUNTO_MEDICION, value))
                {
                    var previousValue = _cAT_PUNTO_MEDICION;
                    _cAT_PUNTO_MEDICION = value;
                    FixupCAT_PUNTO_MEDICION(previousValue);
                }
            }
        }
        private CAT_PUNTO_MEDICION _cAT_PUNTO_MEDICION;

        #endregion
        #region Association Fixup
    
        private void FixupCAT_ESTRUCTURA(CAT_ESTRUCTURA previousValue)
        {
            if (previousValue != null && previousValue.REL_EST_PUNTOMED.Contains(this))
            {
                previousValue.REL_EST_PUNTOMED.Remove(this);
            }
    
            if (CAT_ESTRUCTURA != null)
            {
                if (!CAT_ESTRUCTURA.REL_EST_PUNTOMED.Contains(this))
                {
                    CAT_ESTRUCTURA.REL_EST_PUNTOMED.Add(this);
                }
                if (IdEstructura != CAT_ESTRUCTURA.IdEstructura)
                {
                    IdEstructura = CAT_ESTRUCTURA.IdEstructura;
                }
            }
        }
    
        private void FixupCAT_PUNTO_MEDICION(CAT_PUNTO_MEDICION previousValue)
        {
            if (previousValue != null && previousValue.REL_EST_PUNTOMED.Contains(this))
            {
                previousValue.REL_EST_PUNTOMED.Remove(this);
            }
    
            if (CAT_PUNTO_MEDICION != null)
            {
                if (!CAT_PUNTO_MEDICION.REL_EST_PUNTOMED.Contains(this))
                {
                    CAT_PUNTO_MEDICION.REL_EST_PUNTOMED.Add(this);
                }
                if (IdPuntoMedicion != CAT_PUNTO_MEDICION.IdPuntoMedicion)
                {
                    IdPuntoMedicion = CAT_PUNTO_MEDICION.IdPuntoMedicion;
                }
            }
        }

        #endregion
    }
}
